//auth
export const AUTH_CHANGE_EMAIL_TEXT = "AUTH_CHANGE_EMAIL_TEXT";
export const AUTH_CHANGE_PASSWORD_TEXT = "AUTH_CHANGE_PASSWORD_TEXT";
//registration
export const REGISTRATION_CHANGE_EMAIL_TEXT = "REGISTRATION_CHANGE_EMAIL_TEXT";
export const REGISTRATION_CHANGE_PASSWORD_TEXT =
    "REGISTRATION_CHANGE_PASSWORD_TEXT";
export const REGISTRATION_CHANGE_REPEAT_PASSWORD_TEXT =
    "REGISTRATION_CHANGE_REPEAT_PASSWORD_TEXT";
