
function f1() {
    let div = document.querySelector('.one ');
    div.innerHTML += ' hello';
}

f1();


function f2() {
    let div = document.querySelector('.two ');
    div.innerHTML += ' hello';
}
f2();

// ===================================================

let c = document.querySelector('.three');

function f3() {
    c.innerHTML += ' HELLO';
};

f3();

с = document.querySelector('.four');

f3();


