export const POST_CREATE_POST = "POST_CREATE_POST";
export const POST_FETCH_POSTS = "POST_FETCH_POSTS";
export const LOADER_SHOW_LOADER = "LOADER_SHOW_LOADER";
export const LOADER_HIDE_LOADER = "LOADER_HIDE_LOADER";
export const POST_SHOW_ALERT = "POST_SHOW_ALERT";
export const POST_HIDE_ALERT = "POST_HIDE_ALERT";
export const REQUEST_POSTS = "REQUEST_POSTS";
